
export const GET_TESLA_REQUEST = "GET_TESLA_REQUEST"
export const GET_TESLA_SUCCESS = "GET_TESLA_SUCCESS"
export const GET_TESLA_FAILURE = "GET_TESLA_FAILURE"

export const POST_TESLA_REQUEST = "POST_TESLA_REQUEST"
export const POST_TESLA_SUCCESS = "POST_TESLA_SUCCESS"
export const POST_TESLA_FAILURE = "POST_TESLA_FAILURE"


export const DELETE_TESLA_REQUEST = "DELETE_TESLA_REQUEST"
export const DELETE_TESLA_SUCCESS = "DELETE_TESLA_SUCCESS"
export const DELETE_TESLA_FAILURE = "DELETE_TESLA_FAILURE"


export const EDIT_TESLA_REQUEST = "EDIT_TESLA_REQUEST"
export const EDIT_TESLA_SUCCESS = "EDIT_TESLA_SUCCESS"
export const EDIT_TESLA_FAILURE = "EDIT_TESLA_FAILURE"