export const GET_HOTELS_REQUEST = "GET_HOTELS_REQUEST";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAILURE = "GET_HOTELS_FAILURE";

export const ADD_HOTEL_REQUEST = "ADD_HOTEL_REQUEST";
export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAILURE = "ADD_HOTEL_FAILURE";

export const EDIT_HOTEL_REQUEST = "EDIT_HOTEL_REQUEST";
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS";
export const EDIT_HOTEL_FAILURE = "EDIT_HOTEL_FAILURE";

export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAILURE = "DELETE_HOTEL_FAILURE";
