export const GET_MUSIC_REQUEST = "GET_MUSIC_REQUEST";
export const GET_MUSIC_SUCCESS = "GET_MUSIC_SUCCESS";
export const GET_MUSIC_FAILURE = "GET_MUSIC_FAILURE";

export const EDIT_MUSIC_REQUEST = "EDIT_MUSIC_REQUEST";
export const EDIT_MUSIC_SUCCESS = "EDIT_MUSIC_SUCCESS";
export const EDIT_MUSIC_FAILURE = "EDIT_MUSIC_FAILURE";

