
export const GET_TUITION_REQUEST = "GET_TUITION_REQUEST"
export const GET_TUITION_SUCCESS = "GET_TUITION_SUCCESS"
export const GET_TUITION_FAILURE = "GET_TUITION_FAILURE"

export const POST_TUITION_REQUEST = "POST_TUITION_REQUEST"
export const POST_TUITION_SUCCESS = "POST_TUITION_SUCCESS"
export const POST_TUITION_FAILURE = "POST_TUITION_FAILURE"


export const DELETE_TUITION_REQUEST = "DELETE_TUITION_REQUEST"
export const DELETE_TUITION_SUCCESS = "DELETE_TUITION_SUCCESS"
export const DELETE_TUITION_FAILURE = "DELETE_TUITION_FAILURE"


export const EDIT_TUITION_REQUEST = "EDIT_TUITION_REQUEST"
export const EDIT_TUITION_SUCCESS = "EDIT_TUITION_SUCCESS"
export const EDIT_TUITION_FAILURE = "EDIT_TUITION_FAILURE"
export const DETAILS_SUCCESS = "DETAILS_SUCCESS"