export const GET_RESTAURANT_REQUEST = "GET_MUSIC_REQUEST";
export const GET_RESTAURANT_SUCCESS = "GET_MUSIC_SUCCESS";
export const GET_RESTAURANT_FAILURE = "GET_MUSIC_FAILURE";

export const ADD_RESTAURANT_REQUEST = "ADD_MUSIC_REQUEST";
export const ADD_RESTAURANT_SUCCESS = "ADD_MUSIC_SUCCESS";
export const ADD_RESTAURANT_FAILURE = "ADD_MUSIC_FAILURE";

